### ISSUE TITLE
I have a lot of repos...

### ISSUE THREAD

**Issue by darron** [salesforce/get-you-a-license#3]
...and I'm pretty sure that my repos don't stop alphabetically at `s` - there's a bunch missing.

![screen shot 2018-01-30 at 10 50 51 am](https://user-images.githubusercontent.com/5176/35582335-c67c9a14-05ab-11e8-8b62-833c13fcd323.png)

Is there some sort of limit?

Thanks for a really handy little tool - I was able to add a whole bunch of licenses to repos very quickly.

**Comment by jamesward** [comment]
Thanks for reporting!  Looks like I might have a bug in my paging logic.  I'll investigate.

**Comment by jamesward** [comment]
The fix for this has been deployed.  Let me know if you have any problems.

**Comment by darron** [comment]
Looks great @jamesward - thanks!
